# coding: utf-8

"""
    Allscreenshots public API

    Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allscreenshots_sdk.models.browser_cookie_request import BrowserCookieRequest
from allscreenshots_sdk.models.browser_header_request import BrowserHeaderRequest
from allscreenshots_sdk.models.browser_storage_origin_request import BrowserStorageOriginRequest
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BrowserSessionRequest(BaseModel):
    """
    BrowserSessionRequest
    """ # noqa: E501
    cookies: Optional[Annotated[List[BrowserCookieRequest], Field(min_length=0, max_length=200)]] = None
    headers: Optional[Annotated[List[BrowserHeaderRequest], Field(min_length=0, max_length=100)]] = None
    storage: Optional[Annotated[List[BrowserStorageOriginRequest], Field(min_length=0, max_length=5)]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["cookies", "headers", "storage"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrowserSessionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in cookies (list)
        _items = []
        if self.cookies:
            for _item_cookies in self.cookies:
                _items.append(_item_cookies.to_dict() if _item_cookies is not None else None)
            _dict['cookies'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in headers (list)
        _items = []
        if self.headers:
            for _item_headers in self.headers:
                _items.append(_item_headers.to_dict() if _item_headers is not None else None)
            _dict['headers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in storage (list)
        _items = []
        if self.storage:
            for _item_storage in self.storage:
                _items.append(_item_storage.to_dict() if _item_storage is not None else None)
            _dict['storage'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrowserSessionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cookies": [BrowserCookieRequest.from_dict(_item) for _item in obj["cookies"]] if obj.get("cookies") is not None else None,
            "headers": [BrowserHeaderRequest.from_dict(_item) for _item in obj["headers"]] if obj.get("headers") is not None else None,
            "storage": [BrowserStorageOriginRequest.from_dict(_item) for _item in obj["storage"]] if obj.get("storage") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


