# coding: utf-8

"""
    Allscreenshots public API

    Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allscreenshots_sdk.models.output_spec import OutputSpec
from allscreenshots_sdk.models.page_action import PageAction
from allscreenshots_sdk.models.viewport_config import ViewportConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BulkUrlOptions(BaseModel):
    """
    BulkUrlOptions
    """ # noqa: E501
    actions: Optional[List[PageAction]] = None
    block_ads: Optional[StrictBool] = Field(default=None, alias="blockAds")
    block_cookie_banners: Optional[StrictBool] = Field(default=None, alias="blockCookieBanners")
    block_level: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="blockLevel")
    block_popups: Optional[StrictBool] = Field(default=None, alias="blockPopups")
    custom_css: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=10000)]] = Field(default=None, alias="customCss")
    dark_mode: Optional[StrictBool] = Field(default=None, alias="darkMode")
    delay: Optional[Annotated[int, Field(le=30000, strict=True, ge=0)]] = None
    device: Optional[StrictStr] = None
    format: Optional[Annotated[str, Field(strict=True)]] = None
    full_page: Optional[StrictBool] = Field(default=None, alias="fullPage")
    outputs: Optional[List[OutputSpec]] = None
    quality: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None
    stealth_mode: Optional[StrictBool] = Field(default=None, alias="stealthMode")
    viewport: Optional[ViewportConfig] = None
    wait_for: Optional[StrictStr] = Field(default=None, alias="waitFor")
    wait_until: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="waitUntil")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["actions", "blockAds", "blockCookieBanners", "blockLevel", "blockPopups", "customCss", "darkMode", "delay", "device", "format", "fullPage", "outputs", "quality", "stealthMode", "viewport", "waitFor", "waitUntil"]

    @field_validator('block_level', mode="before")
    def block_level_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(none|light|normal|pro|pro_plus|ultimate)$", value):
            raise ValueError(r"must validate the regular expression /^(none|light|normal|pro|pro_plus|ultimate)$/")
        return value

    @field_validator('format', mode="before")
    def format_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(png|jpeg|jpg|webp|pdf)$", value):
            raise ValueError(r"must validate the regular expression /^(png|jpeg|jpg|webp|pdf)$/")
        return value

    @field_validator('wait_until', mode="before")
    def wait_until_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(load|domcontentloaded|networkidle)$", value):
            raise ValueError(r"must validate the regular expression /^(load|domcontentloaded|networkidle)$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BulkUrlOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in actions (list)
        _items = []
        if self.actions:
            for _item_actions in self.actions:
                _items.append(_item_actions.to_dict() if _item_actions is not None else None)
            _dict['actions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in outputs (list)
        _items = []
        if self.outputs:
            for _item_outputs in self.outputs:
                _items.append(_item_outputs.to_dict() if _item_outputs is not None else None)
            _dict['outputs'] = _items
        # override the default output from pydantic by calling `to_dict()` of viewport
        if self.viewport:
            _dict['viewport'] = self.viewport.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if actions (nullable) is None
        # and model_fields_set contains the field
        if self.actions is None and "actions" in self.model_fields_set:
            _dict['actions'] = None

        # set to None if block_ads (nullable) is None
        # and model_fields_set contains the field
        if self.block_ads is None and "block_ads" in self.model_fields_set:
            _dict['blockAds'] = None

        # set to None if block_cookie_banners (nullable) is None
        # and model_fields_set contains the field
        if self.block_cookie_banners is None and "block_cookie_banners" in self.model_fields_set:
            _dict['blockCookieBanners'] = None

        # set to None if block_level (nullable) is None
        # and model_fields_set contains the field
        if self.block_level is None and "block_level" in self.model_fields_set:
            _dict['blockLevel'] = None

        # set to None if block_popups (nullable) is None
        # and model_fields_set contains the field
        if self.block_popups is None and "block_popups" in self.model_fields_set:
            _dict['blockPopups'] = None

        # set to None if custom_css (nullable) is None
        # and model_fields_set contains the field
        if self.custom_css is None and "custom_css" in self.model_fields_set:
            _dict['customCss'] = None

        # set to None if dark_mode (nullable) is None
        # and model_fields_set contains the field
        if self.dark_mode is None and "dark_mode" in self.model_fields_set:
            _dict['darkMode'] = None

        # set to None if delay (nullable) is None
        # and model_fields_set contains the field
        if self.delay is None and "delay" in self.model_fields_set:
            _dict['delay'] = None

        # set to None if device (nullable) is None
        # and model_fields_set contains the field
        if self.device is None and "device" in self.model_fields_set:
            _dict['device'] = None

        # set to None if format (nullable) is None
        # and model_fields_set contains the field
        if self.format is None and "format" in self.model_fields_set:
            _dict['format'] = None

        # set to None if full_page (nullable) is None
        # and model_fields_set contains the field
        if self.full_page is None and "full_page" in self.model_fields_set:
            _dict['fullPage'] = None

        # set to None if outputs (nullable) is None
        # and model_fields_set contains the field
        if self.outputs is None and "outputs" in self.model_fields_set:
            _dict['outputs'] = None

        # set to None if quality (nullable) is None
        # and model_fields_set contains the field
        if self.quality is None and "quality" in self.model_fields_set:
            _dict['quality'] = None

        # set to None if stealth_mode (nullable) is None
        # and model_fields_set contains the field
        if self.stealth_mode is None and "stealth_mode" in self.model_fields_set:
            _dict['stealthMode'] = None

        # set to None if viewport (nullable) is None
        # and model_fields_set contains the field
        if self.viewport is None and "viewport" in self.model_fields_set:
            _dict['viewport'] = None

        # set to None if wait_for (nullable) is None
        # and model_fields_set contains the field
        if self.wait_for is None and "wait_for" in self.model_fields_set:
            _dict['waitFor'] = None

        # set to None if wait_until (nullable) is None
        # and model_fields_set contains the field
        if self.wait_until is None and "wait_until" in self.model_fields_set:
            _dict['waitUntil'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BulkUrlOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "actions": [PageAction.from_dict(_item) for _item in obj["actions"]] if obj.get("actions") is not None else None,
            "blockAds": obj.get("blockAds"),
            "blockCookieBanners": obj.get("blockCookieBanners"),
            "blockLevel": obj.get("blockLevel"),
            "blockPopups": obj.get("blockPopups"),
            "customCss": obj.get("customCss"),
            "darkMode": obj.get("darkMode"),
            "delay": obj.get("delay"),
            "device": obj.get("device"),
            "format": obj.get("format"),
            "fullPage": obj.get("fullPage"),
            "outputs": [OutputSpec.from_dict(_item) for _item in obj["outputs"]] if obj.get("outputs") is not None else None,
            "quality": obj.get("quality"),
            "stealthMode": obj.get("stealthMode"),
            "viewport": ViewportConfig.from_dict(obj["viewport"]) if obj.get("viewport") is not None else None,
            "waitFor": obj.get("waitFor"),
            "waitUntil": obj.get("waitUntil")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


