# coding: utf-8

"""
    Allscreenshots public API

    Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BulkJobSummary(BaseModel):
    """
    BulkJobSummary
    """ # noqa: E501
    completed_at: Optional[datetime] = Field(default=None, alias="completedAt")
    completed_jobs: StrictInt = Field(alias="completedJobs")
    created_at: datetime = Field(alias="createdAt")
    failed_jobs: StrictInt = Field(alias="failedJobs")
    id: StrictStr
    progress: StrictInt
    status: StrictStr
    total_jobs: StrictInt = Field(alias="totalJobs")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["completedAt", "completedJobs", "createdAt", "failedJobs", "id", "progress", "status", "totalJobs"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BulkJobSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BulkJobSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "completedAt": obj.get("completedAt"),
            "completedJobs": obj.get("completedJobs"),
            "createdAt": obj.get("createdAt"),
            "failedJobs": obj.get("failedJobs"),
            "id": obj.get("id"),
            "progress": obj.get("progress"),
            "status": obj.get("status"),
            "totalJobs": obj.get("totalJobs")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


