# coding: utf-8

"""
    Allscreenshots public API

    Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allscreenshots_sdk.models.bulk_defaults import BulkDefaults
from allscreenshots_sdk.models.bulk_url_request import BulkUrlRequest
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BulkRequest(BaseModel):
    """
    BulkRequest
    """ # noqa: E501
    defaults: Optional[BulkDefaults] = None
    urls: Annotated[List[BulkUrlRequest], Field(min_length=0, max_length=100)]
    webhook_secret: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=255)]] = Field(default=None, alias="webhookSecret")
    webhook_url: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="webhookUrl")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["defaults", "urls", "webhookSecret", "webhookUrl"]

    @field_validator('webhook_url', mode="before")
    def webhook_url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^https?:\/\/.*", value):
            raise ValueError(r"must validate the regular expression /^https?:\/\/.*/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BulkRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of defaults
        if self.defaults:
            _dict['defaults'] = self.defaults.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in urls (list)
        _items = []
        if self.urls:
            for _item_urls in self.urls:
                _items.append(_item_urls.to_dict() if _item_urls is not None else None)
            _dict['urls'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if defaults (nullable) is None
        # and model_fields_set contains the field
        if self.defaults is None and "defaults" in self.model_fields_set:
            _dict['defaults'] = None

        # set to None if webhook_secret (nullable) is None
        # and model_fields_set contains the field
        if self.webhook_secret is None and "webhook_secret" in self.model_fields_set:
            _dict['webhookSecret'] = None

        # set to None if webhook_url (nullable) is None
        # and model_fields_set contains the field
        if self.webhook_url is None and "webhook_url" in self.model_fields_set:
            _dict['webhookUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BulkRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "defaults": BulkDefaults.from_dict(obj["defaults"]) if obj.get("defaults") is not None else None,
            "urls": [BulkUrlRequest.from_dict(_item) for _item in obj["urls"]] if obj.get("urls") is not None else None,
            "webhookSecret": obj.get("webhookSecret"),
            "webhookUrl": obj.get("webhookUrl")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


