# coding: utf-8

"""
    Allscreenshots public API

    Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from allscreenshots_sdk.models.compose_metadata import ComposeMetadata
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ComposeResponse(BaseModel):
    """
    ComposeResponse
    """ # noqa: E501
    expires_at: datetime = Field(alias="expiresAt")
    file_size: StrictInt = Field(alias="fileSize")
    format: StrictStr
    height: StrictInt
    layout: StrictStr
    metadata: ComposeMetadata
    render_time_ms: StrictInt = Field(alias="renderTimeMs")
    storage_url: Optional[StrictStr] = Field(default=None, alias="storageUrl")
    url: StrictStr
    width: StrictInt
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["expiresAt", "fileSize", "format", "height", "layout", "metadata", "renderTimeMs", "storageUrl", "url", "width"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ComposeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if storage_url (nullable) is None
        # and model_fields_set contains the field
        if self.storage_url is None and "storage_url" in self.model_fields_set:
            _dict['storageUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ComposeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "expiresAt": obj.get("expiresAt"),
            "fileSize": obj.get("fileSize"),
            "format": obj.get("format"),
            "height": obj.get("height"),
            "layout": obj.get("layout"),
            "metadata": ComposeMetadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
            "renderTimeMs": obj.get("renderTimeMs"),
            "storageUrl": obj.get("storageUrl"),
            "url": obj.get("url"),
            "width": obj.get("width")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


