# coding: utf-8

"""
    Allscreenshots public API

    Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allscreenshots_sdk.models.border_config import BorderConfig
from allscreenshots_sdk.models.label_config import LabelConfig
from allscreenshots_sdk.models.shadow_config import ShadowConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ComposeOutputConfig(BaseModel):
    """
    ComposeOutputConfig
    """ # noqa: E501
    alignment: Optional[Annotated[str, Field(strict=True)]] = 'center'
    background: Optional[Annotated[str, Field(strict=True)]] = '#ffffff'
    border: Optional[BorderConfig] = None
    columns: Optional[Annotated[int, Field(le=10, strict=True, ge=1)]] = None
    format: Optional[Annotated[str, Field(strict=True)]] = 'png'
    labels: Optional[LabelConfig] = None
    layout: Optional[StrictStr] = 'AUTO'
    max_height: Optional[Annotated[int, Field(le=10000, strict=True, ge=100)]] = Field(default=None, alias="maxHeight")
    max_width: Optional[Annotated[int, Field(le=10000, strict=True, ge=100)]] = Field(default=None, alias="maxWidth")
    padding: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = 0
    quality: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = 90
    shadow: Optional[ShadowConfig] = None
    spacing: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = 10
    thumbnail_width: Optional[Annotated[int, Field(le=2000, strict=True, ge=50)]] = Field(default=None, alias="thumbnailWidth")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["alignment", "background", "border", "columns", "format", "labels", "layout", "maxHeight", "maxWidth", "padding", "quality", "shadow", "spacing", "thumbnailWidth"]

    @field_validator('alignment', mode="before")
    def alignment_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(top|center|bottom)$", value):
            raise ValueError(r"must validate the regular expression /^(top|center|bottom)$/")
        return value

    @field_validator('background', mode="before")
    def background_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(#[0-9A-Fa-f]{6}|#[0-9A-Fa-f]{8}|transparent)$", value):
            raise ValueError(r"must validate the regular expression /^(#[0-9A-Fa-f]{6}|#[0-9A-Fa-f]{8}|transparent)$/")
        return value

    @field_validator('format', mode="before")
    def format_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(png|jpeg|jpg|webp)$", value):
            raise ValueError(r"must validate the regular expression /^(png|jpeg|jpg|webp)$/")
        return value

    @field_validator('layout')
    def layout_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['GRID', 'HORIZONTAL', 'VERTICAL', 'MASONRY', 'MONDRIAN', 'PARTITIONING', 'AUTO']):
            raise ValueError("must be one of enum values ('GRID', 'HORIZONTAL', 'VERTICAL', 'MASONRY', 'MONDRIAN', 'PARTITIONING', 'AUTO')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ComposeOutputConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of border
        if self.border:
            _dict['border'] = self.border.to_dict()
        # override the default output from pydantic by calling `to_dict()` of labels
        if self.labels:
            _dict['labels'] = self.labels.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shadow
        if self.shadow:
            _dict['shadow'] = self.shadow.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if border (nullable) is None
        # and model_fields_set contains the field
        if self.border is None and "border" in self.model_fields_set:
            _dict['border'] = None

        # set to None if columns (nullable) is None
        # and model_fields_set contains the field
        if self.columns is None and "columns" in self.model_fields_set:
            _dict['columns'] = None

        # set to None if labels (nullable) is None
        # and model_fields_set contains the field
        if self.labels is None and "labels" in self.model_fields_set:
            _dict['labels'] = None

        # set to None if max_height (nullable) is None
        # and model_fields_set contains the field
        if self.max_height is None and "max_height" in self.model_fields_set:
            _dict['maxHeight'] = None

        # set to None if max_width (nullable) is None
        # and model_fields_set contains the field
        if self.max_width is None and "max_width" in self.model_fields_set:
            _dict['maxWidth'] = None

        # set to None if shadow (nullable) is None
        # and model_fields_set contains the field
        if self.shadow is None and "shadow" in self.model_fields_set:
            _dict['shadow'] = None

        # set to None if thumbnail_width (nullable) is None
        # and model_fields_set contains the field
        if self.thumbnail_width is None and "thumbnail_width" in self.model_fields_set:
            _dict['thumbnailWidth'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ComposeOutputConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alignment": obj.get("alignment") if obj.get("alignment") is not None else 'center',
            "background": obj.get("background") if obj.get("background") is not None else '#ffffff',
            "border": BorderConfig.from_dict(obj["border"]) if obj.get("border") is not None else None,
            "columns": obj.get("columns"),
            "format": obj.get("format") if obj.get("format") is not None else 'png',
            "labels": LabelConfig.from_dict(obj["labels"]) if obj.get("labels") is not None else None,
            "layout": obj.get("layout") if obj.get("layout") is not None else 'AUTO',
            "maxHeight": obj.get("maxHeight"),
            "maxWidth": obj.get("maxWidth"),
            "padding": obj.get("padding") if obj.get("padding") is not None else 0,
            "quality": obj.get("quality") if obj.get("quality") is not None else 90,
            "shadow": ShadowConfig.from_dict(obj["shadow"]) if obj.get("shadow") is not None else None,
            "spacing": obj.get("spacing") if obj.get("spacing") is not None else 10,
            "thumbnailWidth": obj.get("thumbnailWidth")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


