# coding: utf-8

"""
    Allscreenshots public API

    Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from allscreenshots_sdk.models.output_spec import OutputSpec
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CrawlPageResponse(BaseModel):
    """
    CrawlPageResponse
    """ # noqa: E501
    canonical_url: Optional[StrictStr] = Field(default=None, alias="canonicalUrl")
    completed_at: Optional[datetime] = Field(default=None, alias="completedAt")
    content_type: Optional[StrictStr] = Field(default=None, alias="contentType")
    created_at: datetime = Field(alias="createdAt")
    depth: StrictInt
    description: Optional[StrictStr] = None
    error_code: Optional[StrictStr] = Field(default=None, alias="errorCode")
    error_message: Optional[StrictStr] = Field(default=None, alias="errorMessage")
    http_status: Optional[StrictInt] = Field(default=None, alias="httpStatus")
    id: StrictStr
    language: Optional[StrictStr] = None
    outputs: List[OutputSpec]
    parent_id: Optional[StrictStr] = Field(default=None, alias="parentId")
    render_time_ms: Optional[StrictInt] = Field(default=None, alias="renderTimeMs")
    status: StrictStr
    title: Optional[StrictStr] = None
    url: StrictStr
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["canonicalUrl", "completedAt", "contentType", "createdAt", "depth", "description", "errorCode", "errorMessage", "httpStatus", "id", "language", "outputs", "parentId", "renderTimeMs", "status", "title", "url"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', 'CANCELLED']):
            raise ValueError("must be one of enum values ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', 'CANCELLED')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CrawlPageResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in outputs (list)
        _items = []
        if self.outputs:
            for _item_outputs in self.outputs:
                _items.append(_item_outputs.to_dict() if _item_outputs is not None else None)
            _dict['outputs'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if canonical_url (nullable) is None
        # and model_fields_set contains the field
        if self.canonical_url is None and "canonical_url" in self.model_fields_set:
            _dict['canonicalUrl'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completedAt'] = None

        # set to None if content_type (nullable) is None
        # and model_fields_set contains the field
        if self.content_type is None and "content_type" in self.model_fields_set:
            _dict['contentType'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if error_code (nullable) is None
        # and model_fields_set contains the field
        if self.error_code is None and "error_code" in self.model_fields_set:
            _dict['errorCode'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['errorMessage'] = None

        # set to None if http_status (nullable) is None
        # and model_fields_set contains the field
        if self.http_status is None and "http_status" in self.model_fields_set:
            _dict['httpStatus'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if parent_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_id is None and "parent_id" in self.model_fields_set:
            _dict['parentId'] = None

        # set to None if render_time_ms (nullable) is None
        # and model_fields_set contains the field
        if self.render_time_ms is None and "render_time_ms" in self.model_fields_set:
            _dict['renderTimeMs'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CrawlPageResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "canonicalUrl": obj.get("canonicalUrl"),
            "completedAt": obj.get("completedAt"),
            "contentType": obj.get("contentType"),
            "createdAt": obj.get("createdAt"),
            "depth": obj.get("depth"),
            "description": obj.get("description"),
            "errorCode": obj.get("errorCode"),
            "errorMessage": obj.get("errorMessage"),
            "httpStatus": obj.get("httpStatus"),
            "id": obj.get("id"),
            "language": obj.get("language"),
            "outputs": [OutputSpec.from_dict(_item) for _item in obj["outputs"]] if obj.get("outputs") is not None else None,
            "parentId": obj.get("parentId"),
            "renderTimeMs": obj.get("renderTimeMs"),
            "status": obj.get("status"),
            "title": obj.get("title"),
            "url": obj.get("url")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


