# coding: utf-8

"""
    Allscreenshots public API

    Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allscreenshots_sdk.models.output_spec import OutputSpec
from allscreenshots_sdk.models.viewport_config import ViewportConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CrawlRequest(BaseModel):
    """
    CrawlRequest
    """ # noqa: E501
    block_ads: Optional[StrictBool] = Field(default=True, alias="blockAds")
    block_cookie_banners: Optional[StrictBool] = Field(default=True, alias="blockCookieBanners")
    block_popups: Optional[StrictBool] = Field(default=True, alias="blockPopups")
    crawl_delay_ms: Optional[Annotated[int, Field(le=30000, strict=True, ge=500)]] = Field(default=500, alias="crawlDelayMs")
    dark_mode: Optional[StrictBool] = Field(default=False, alias="darkMode")
    depth: Optional[Annotated[int, Field(le=5, strict=True, ge=0)]] = 2
    exclude_patterns: Optional[Annotated[List[StrictStr], Field(min_length=0, max_length=25)]] = Field(default=None, alias="excludePatterns")
    format: Optional[Annotated[str, Field(strict=True)]] = 'png'
    full_page: Optional[StrictBool] = Field(default=True, alias="fullPage")
    include_patterns: Optional[Annotated[List[StrictStr], Field(min_length=0, max_length=25)]] = Field(default=None, alias="includePatterns")
    include_subdomains: Optional[StrictBool] = Field(default=False, alias="includeSubdomains")
    limit: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = 25
    outputs: Optional[Annotated[List[OutputSpec], Field(min_length=1, max_length=4)]] = None
    quality: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = 80
    render_delay: Optional[Annotated[int, Field(le=30000, strict=True, ge=0)]] = Field(default=0, alias="renderDelay")
    timeout: Optional[Annotated[int, Field(le=60000, strict=True, ge=1000)]] = 30000
    url: Annotated[str, Field(min_length=1, strict=True)]
    viewport: Optional[ViewportConfig] = None
    wait_until: Optional[Annotated[str, Field(strict=True)]] = Field(default='domcontentloaded', alias="waitUntil")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["blockAds", "blockCookieBanners", "blockPopups", "crawlDelayMs", "darkMode", "depth", "excludePatterns", "format", "fullPage", "includePatterns", "includeSubdomains", "limit", "outputs", "quality", "renderDelay", "timeout", "url", "viewport", "waitUntil"]

    @field_validator('format', mode="before")
    def format_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(png|jpeg|jpg)$", value):
            raise ValueError(r"must validate the regular expression /^(png|jpeg|jpg)$/")
        return value

    @field_validator('url', mode="before")
    def url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^https?:\/\/.*", value):
            raise ValueError(r"must validate the regular expression /^https?:\/\/.*/")
        return value

    @field_validator('wait_until', mode="before")
    def wait_until_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(load|domcontentloaded|networkidle)$", value):
            raise ValueError(r"must validate the regular expression /^(load|domcontentloaded|networkidle)$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CrawlRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in outputs (list)
        _items = []
        if self.outputs:
            for _item_outputs in self.outputs:
                _items.append(_item_outputs.to_dict() if _item_outputs is not None else None)
            _dict['outputs'] = _items
        # override the default output from pydantic by calling `to_dict()` of viewport
        if self.viewport:
            _dict['viewport'] = self.viewport.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CrawlRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "blockAds": obj.get("blockAds") if obj.get("blockAds") is not None else True,
            "blockCookieBanners": obj.get("blockCookieBanners") if obj.get("blockCookieBanners") is not None else True,
            "blockPopups": obj.get("blockPopups") if obj.get("blockPopups") is not None else True,
            "crawlDelayMs": obj.get("crawlDelayMs") if obj.get("crawlDelayMs") is not None else 500,
            "darkMode": obj.get("darkMode") if obj.get("darkMode") is not None else False,
            "depth": obj.get("depth") if obj.get("depth") is not None else 2,
            "excludePatterns": obj.get("excludePatterns"),
            "format": obj.get("format") if obj.get("format") is not None else 'png',
            "fullPage": obj.get("fullPage") if obj.get("fullPage") is not None else True,
            "includePatterns": obj.get("includePatterns"),
            "includeSubdomains": obj.get("includeSubdomains") if obj.get("includeSubdomains") is not None else False,
            "limit": obj.get("limit") if obj.get("limit") is not None else 25,
            "outputs": [OutputSpec.from_dict(_item) for _item in obj["outputs"]] if obj.get("outputs") is not None else None,
            "quality": obj.get("quality") if obj.get("quality") is not None else 80,
            "renderDelay": obj.get("renderDelay") if obj.get("renderDelay") is not None else 0,
            "timeout": obj.get("timeout") if obj.get("timeout") is not None else 30000,
            "url": obj.get("url"),
            "viewport": ViewportConfig.from_dict(obj["viewport"]) if obj.get("viewport") is not None else None,
            "waitUntil": obj.get("waitUntil") if obj.get("waitUntil") is not None else 'domcontentloaded'
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


