# coding: utf-8

"""
    Allscreenshots public API

    Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LabelConfig(BaseModel):
    """
    LabelConfig
    """ # noqa: E501
    background: Optional[StrictStr] = '#ffffff'
    font_color: Optional[StrictStr] = Field(default='#333333', alias="fontColor")
    font_size: Optional[Annotated[int, Field(le=48, strict=True, ge=8)]] = Field(default=14, alias="fontSize")
    padding: Optional[Annotated[int, Field(le=20, strict=True, ge=0)]] = 8
    position: Optional[Annotated[str, Field(strict=True)]] = 'bottom'
    show: Optional[StrictBool] = True
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["background", "fontColor", "fontSize", "padding", "position", "show"]

    @field_validator('position', mode="before")
    def position_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(top|bottom)$", value):
            raise ValueError(r"must validate the regular expression /^(top|bottom)$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LabelConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LabelConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "background": obj.get("background") if obj.get("background") is not None else '#ffffff',
            "fontColor": obj.get("fontColor") if obj.get("fontColor") is not None else '#333333',
            "fontSize": obj.get("fontSize") if obj.get("fontSize") is not None else 14,
            "padding": obj.get("padding") if obj.get("padding") is not None else 8,
            "position": obj.get("position") if obj.get("position") is not None else 'bottom',
            "show": obj.get("show") if obj.get("show") is not None else True
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


