# coding: utf-8

"""
    Allscreenshots public API

    Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from allscreenshots_sdk.models.click_action import ClickAction
from allscreenshots_sdk.models.hover_action import HoverAction
from allscreenshots_sdk.models.press_action import PressAction
from allscreenshots_sdk.models.scroll_action import ScrollAction
from allscreenshots_sdk.models.select_action import SelectAction
from allscreenshots_sdk.models.type_action import TypeAction
from allscreenshots_sdk.models.wait_action import WaitAction
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

PAGEACTION_ONE_OF_SCHEMAS = ["ClickAction", "HoverAction", "PressAction", "ScrollAction", "SelectAction", "TypeAction", "WaitAction"]

class PageAction(BaseModel):
    """
    PageAction
    """
    # data type: ClickAction
    oneof_schema_1_validator: Optional[ClickAction] = None
    # data type: TypeAction
    oneof_schema_2_validator: Optional[TypeAction] = None
    # data type: PressAction
    oneof_schema_3_validator: Optional[PressAction] = None
    # data type: HoverAction
    oneof_schema_4_validator: Optional[HoverAction] = None
    # data type: SelectAction
    oneof_schema_5_validator: Optional[SelectAction] = None
    # data type: ScrollAction
    oneof_schema_6_validator: Optional[ScrollAction] = None
    # data type: WaitAction
    oneof_schema_7_validator: Optional[WaitAction] = None
    actual_instance: Optional[Union[ClickAction, HoverAction, PressAction, ScrollAction, SelectAction, TypeAction, WaitAction]] = None
    one_of_schemas: Set[str] = { "ClickAction", "HoverAction", "PressAction", "ScrollAction", "SelectAction", "TypeAction", "WaitAction" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = PageAction.model_construct()
        error_messages = []
        match = 0
        # validate data type: ClickAction
        if not isinstance(v, ClickAction):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ClickAction`")
        else:
            match += 1
        # validate data type: TypeAction
        if not isinstance(v, TypeAction):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TypeAction`")
        else:
            match += 1
        # validate data type: PressAction
        if not isinstance(v, PressAction):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PressAction`")
        else:
            match += 1
        # validate data type: HoverAction
        if not isinstance(v, HoverAction):
            error_messages.append(f"Error! Input type `{type(v)}` is not `HoverAction`")
        else:
            match += 1
        # validate data type: SelectAction
        if not isinstance(v, SelectAction):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SelectAction`")
        else:
            match += 1
        # validate data type: ScrollAction
        if not isinstance(v, ScrollAction):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ScrollAction`")
        else:
            match += 1
        # validate data type: WaitAction
        if not isinstance(v, WaitAction):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WaitAction`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in PageAction with oneOf schemas: ClickAction, HoverAction, PressAction, ScrollAction, SelectAction, TypeAction, WaitAction. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in PageAction with oneOf schemas: ClickAction, HoverAction, PressAction, ScrollAction, SelectAction, TypeAction, WaitAction. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ClickAction
        try:
            instance.actual_instance = ClickAction.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TypeAction
        try:
            instance.actual_instance = TypeAction.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PressAction
        try:
            instance.actual_instance = PressAction.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into HoverAction
        try:
            instance.actual_instance = HoverAction.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SelectAction
        try:
            instance.actual_instance = SelectAction.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ScrollAction
        try:
            instance.actual_instance = ScrollAction.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WaitAction
        try:
            instance.actual_instance = WaitAction.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into PageAction with oneOf schemas: ClickAction, HoverAction, PressAction, ScrollAction, SelectAction, TypeAction, WaitAction. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into PageAction with oneOf schemas: ClickAction, HoverAction, PressAction, ScrollAction, SelectAction, TypeAction, WaitAction. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ClickAction, HoverAction, PressAction, ScrollAction, SelectAction, TypeAction, WaitAction]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


