# coding: utf-8

"""
    Allscreenshots public API

    Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from allscreenshots_sdk.models.delivery_destination import DeliveryDestination
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScheduleResponse(BaseModel):
    """
    ScheduleResponse
    """ # noqa: E501
    alert_on_failure: StrictBool = Field(alias="alertOnFailure")
    auto_pause_after_failures: Optional[StrictInt] = Field(default=None, alias="autoPauseAfterFailures")
    consecutive_failures: StrictInt = Field(alias="consecutiveFailures")
    created_at: datetime = Field(alias="createdAt")
    destinations: Optional[List[DeliveryDestination]] = None
    diff_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="diffThreshold")
    ends_at: Optional[datetime] = Field(default=None, alias="endsAt")
    execution_count: StrictInt = Field(alias="executionCount")
    failure_count: StrictInt = Field(alias="failureCount")
    id: StrictStr
    last_executed_at: Optional[datetime] = Field(default=None, alias="lastExecutedAt")
    name: StrictStr
    next_execution_at: Optional[datetime] = Field(default=None, alias="nextExecutionAt")
    only_on_change: StrictBool = Field(alias="onlyOnChange")
    options: Optional[Dict[str, Dict[str, Any]]] = None
    retention_days: StrictInt = Field(alias="retentionDays")
    schedule: StrictStr
    schedule_description: StrictStr = Field(alias="scheduleDescription")
    starts_at: Optional[datetime] = Field(default=None, alias="startsAt")
    status: StrictStr
    success_count: StrictInt = Field(alias="successCount")
    timezone: StrictStr
    updated_at: datetime = Field(alias="updatedAt")
    url: StrictStr
    webhook_url: Optional[StrictStr] = Field(default=None, alias="webhookUrl")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["alertOnFailure", "autoPauseAfterFailures", "consecutiveFailures", "createdAt", "destinations", "diffThreshold", "endsAt", "executionCount", "failureCount", "id", "lastExecutedAt", "name", "nextExecutionAt", "onlyOnChange", "options", "retentionDays", "schedule", "scheduleDescription", "startsAt", "status", "successCount", "timezone", "updatedAt", "url", "webhookUrl"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScheduleResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in destinations (list)
        _items = []
        if self.destinations:
            for _item_destinations in self.destinations:
                _items.append(_item_destinations.to_dict() if _item_destinations is not None else None)
            _dict['destinations'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if auto_pause_after_failures (nullable) is None
        # and model_fields_set contains the field
        if self.auto_pause_after_failures is None and "auto_pause_after_failures" in self.model_fields_set:
            _dict['autoPauseAfterFailures'] = None

        # set to None if destinations (nullable) is None
        # and model_fields_set contains the field
        if self.destinations is None and "destinations" in self.model_fields_set:
            _dict['destinations'] = None

        # set to None if diff_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.diff_threshold is None and "diff_threshold" in self.model_fields_set:
            _dict['diffThreshold'] = None

        # set to None if ends_at (nullable) is None
        # and model_fields_set contains the field
        if self.ends_at is None and "ends_at" in self.model_fields_set:
            _dict['endsAt'] = None

        # set to None if last_executed_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_executed_at is None and "last_executed_at" in self.model_fields_set:
            _dict['lastExecutedAt'] = None

        # set to None if next_execution_at (nullable) is None
        # and model_fields_set contains the field
        if self.next_execution_at is None and "next_execution_at" in self.model_fields_set:
            _dict['nextExecutionAt'] = None

        # set to None if options (nullable) is None
        # and model_fields_set contains the field
        if self.options is None and "options" in self.model_fields_set:
            _dict['options'] = None

        # set to None if starts_at (nullable) is None
        # and model_fields_set contains the field
        if self.starts_at is None and "starts_at" in self.model_fields_set:
            _dict['startsAt'] = None

        # set to None if webhook_url (nullable) is None
        # and model_fields_set contains the field
        if self.webhook_url is None and "webhook_url" in self.model_fields_set:
            _dict['webhookUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScheduleResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alertOnFailure": obj.get("alertOnFailure"),
            "autoPauseAfterFailures": obj.get("autoPauseAfterFailures"),
            "consecutiveFailures": obj.get("consecutiveFailures"),
            "createdAt": obj.get("createdAt"),
            "destinations": [DeliveryDestination.from_dict(_item) for _item in obj["destinations"]] if obj.get("destinations") is not None else None,
            "diffThreshold": obj.get("diffThreshold"),
            "endsAt": obj.get("endsAt"),
            "executionCount": obj.get("executionCount"),
            "failureCount": obj.get("failureCount"),
            "id": obj.get("id"),
            "lastExecutedAt": obj.get("lastExecutedAt"),
            "name": obj.get("name"),
            "nextExecutionAt": obj.get("nextExecutionAt"),
            "onlyOnChange": obj.get("onlyOnChange"),
            "options": obj.get("options"),
            "retentionDays": obj.get("retentionDays"),
            "schedule": obj.get("schedule"),
            "scheduleDescription": obj.get("scheduleDescription"),
            "startsAt": obj.get("startsAt"),
            "status": obj.get("status"),
            "successCount": obj.get("successCount"),
            "timezone": obj.get("timezone"),
            "updatedAt": obj.get("updatedAt"),
            "url": obj.get("url"),
            "webhookUrl": obj.get("webhookUrl")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


