# coding: utf-8

"""
    Allscreenshots public API

    Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScheduleExecutionResponse(BaseModel):
    """
    ScheduleExecutionResponse
    """ # noqa: E501
    changed: Optional[StrictBool] = None
    deliveries: Optional[List[Dict[str, Dict[str, Any]]]] = None
    diff_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="diffScore")
    error_code: Optional[StrictStr] = Field(default=None, alias="errorCode")
    error_message: Optional[StrictStr] = Field(default=None, alias="errorMessage")
    executed_at: datetime = Field(alias="executedAt")
    expires_at: Optional[datetime] = Field(default=None, alias="expiresAt")
    file_size: Optional[StrictInt] = Field(default=None, alias="fileSize")
    id: StrictStr
    outputs: Optional[Dict[str, Dict[str, Any]]] = None
    render_time_ms: Optional[StrictInt] = Field(default=None, alias="renderTimeMs")
    result_url: Optional[StrictStr] = Field(default=None, alias="resultUrl")
    run_id: Optional[StrictStr] = Field(default=None, alias="runId")
    status: StrictStr
    storage_url: Optional[StrictStr] = Field(default=None, alias="storageUrl")
    url: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["changed", "deliveries", "diffScore", "errorCode", "errorMessage", "executedAt", "expiresAt", "fileSize", "id", "outputs", "renderTimeMs", "resultUrl", "runId", "status", "storageUrl", "url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScheduleExecutionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if changed (nullable) is None
        # and model_fields_set contains the field
        if self.changed is None and "changed" in self.model_fields_set:
            _dict['changed'] = None

        # set to None if deliveries (nullable) is None
        # and model_fields_set contains the field
        if self.deliveries is None and "deliveries" in self.model_fields_set:
            _dict['deliveries'] = None

        # set to None if diff_score (nullable) is None
        # and model_fields_set contains the field
        if self.diff_score is None and "diff_score" in self.model_fields_set:
            _dict['diffScore'] = None

        # set to None if error_code (nullable) is None
        # and model_fields_set contains the field
        if self.error_code is None and "error_code" in self.model_fields_set:
            _dict['errorCode'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['errorMessage'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expiresAt'] = None

        # set to None if file_size (nullable) is None
        # and model_fields_set contains the field
        if self.file_size is None and "file_size" in self.model_fields_set:
            _dict['fileSize'] = None

        # set to None if outputs (nullable) is None
        # and model_fields_set contains the field
        if self.outputs is None and "outputs" in self.model_fields_set:
            _dict['outputs'] = None

        # set to None if render_time_ms (nullable) is None
        # and model_fields_set contains the field
        if self.render_time_ms is None and "render_time_ms" in self.model_fields_set:
            _dict['renderTimeMs'] = None

        # set to None if result_url (nullable) is None
        # and model_fields_set contains the field
        if self.result_url is None and "result_url" in self.model_fields_set:
            _dict['resultUrl'] = None

        # set to None if run_id (nullable) is None
        # and model_fields_set contains the field
        if self.run_id is None and "run_id" in self.model_fields_set:
            _dict['runId'] = None

        # set to None if storage_url (nullable) is None
        # and model_fields_set contains the field
        if self.storage_url is None and "storage_url" in self.model_fields_set:
            _dict['storageUrl'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScheduleExecutionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "changed": obj.get("changed"),
            "deliveries": obj.get("deliveries"),
            "diffScore": obj.get("diffScore"),
            "errorCode": obj.get("errorCode"),
            "errorMessage": obj.get("errorMessage"),
            "executedAt": obj.get("executedAt"),
            "expiresAt": obj.get("expiresAt"),
            "fileSize": obj.get("fileSize"),
            "id": obj.get("id"),
            "outputs": obj.get("outputs"),
            "renderTimeMs": obj.get("renderTimeMs"),
            "resultUrl": obj.get("resultUrl"),
            "runId": obj.get("runId"),
            "status": obj.get("status"),
            "storageUrl": obj.get("storageUrl"),
            "url": obj.get("url")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


