# coding: utf-8

"""
    Allscreenshots public API

    Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from allscreenshots_sdk.models.browser_session_request import BrowserSessionRequest
from allscreenshots_sdk.models.output_spec import OutputSpec
from allscreenshots_sdk.models.page_action import PageAction
from allscreenshots_sdk.models.viewport_config import ViewportConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScreenshotRequest(BaseModel):
    """
    ScreenshotRequest
    """ # noqa: E501
    actions: Optional[Annotated[List[PageAction], Field(min_length=0, max_length=25)]] = None
    block_ads: Optional[StrictBool] = Field(default=True, alias="blockAds")
    block_cookie_banners: Optional[StrictBool] = Field(default=True, alias="blockCookieBanners")
    block_level: Optional[Annotated[str, Field(strict=True)]] = Field(default='none', alias="blockLevel")
    block_popups: Optional[StrictBool] = Field(default=True, alias="blockPopups")
    custom_css: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=10000)]] = Field(default=None, alias="customCss")
    dark_mode: Optional[StrictBool] = Field(default=False, alias="darkMode")
    delay: Optional[Annotated[int, Field(le=30000, strict=True, ge=0)]] = 0
    device: Optional[StrictStr] = None
    format: Optional[Annotated[str, Field(strict=True)]] = 'png'
    freeze_fixed: Optional[StrictBool] = Field(default=True, alias="freezeFixed")
    full_page: Optional[StrictBool] = Field(default=False, alias="fullPage")
    full_page_mode: Optional[Annotated[str, Field(strict=True)]] = Field(default='stitch', alias="fullPageMode")
    hide_selectors: Optional[Annotated[List[StrictStr], Field(min_length=0, max_length=50)]] = Field(default=None, alias="hideSelectors")
    max_height: Optional[Annotated[int, Field(le=30000, strict=True, ge=1000)]] = Field(default=None, alias="maxHeight")
    max_sections: Optional[Annotated[int, Field(le=50, strict=True, ge=1)]] = Field(default=50, alias="maxSections")
    outputs: Optional[List[OutputSpec]] = None
    quality: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = 80
    response_type: Optional[StrictStr] = Field(default='BINARY', alias="responseType")
    scroll_interval: Optional[Annotated[int, Field(le=1000, strict=True, ge=50)]] = Field(default=150, alias="scrollInterval")
    selector: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=500)]] = None
    session: Optional[BrowserSessionRequest] = None
    stealth_mode: Optional[StrictBool] = Field(default=False, alias="stealthMode")
    timeout: Optional[Annotated[int, Field(le=60000, strict=True, ge=1000)]] = 30000
    url: Annotated[str, Field(min_length=1, strict=True)]
    viewport: Optional[ViewportConfig] = None
    wait_for: Optional[StrictStr] = Field(default=None, alias="waitFor")
    wait_until: Optional[Annotated[str, Field(strict=True)]] = Field(default='domcontentloaded', alias="waitUntil")
    webhook_secret: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=255)]] = Field(default=None, alias="webhookSecret")
    webhook_url: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="webhookUrl")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["actions", "blockAds", "blockCookieBanners", "blockLevel", "blockPopups", "customCss", "darkMode", "delay", "device", "format", "freezeFixed", "fullPage", "fullPageMode", "hideSelectors", "maxHeight", "maxSections", "outputs", "quality", "responseType", "scrollInterval", "selector", "session", "stealthMode", "timeout", "url", "viewport", "waitFor", "waitUntil", "webhookSecret", "webhookUrl"]

    @field_validator('block_level', mode="before")
    def block_level_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(none|light|normal|pro|pro_plus|ultimate)$", value):
            raise ValueError(r"must validate the regular expression /^(none|light|normal|pro|pro_plus|ultimate)$/")
        return value

    @field_validator('format', mode="before")
    def format_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(png|jpeg|jpg|webp|pdf)$", value):
            raise ValueError(r"must validate the regular expression /^(png|jpeg|jpg|webp|pdf)$/")
        return value

    @field_validator('full_page_mode', mode="before")
    def full_page_mode_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(native|stitch)$", value):
            raise ValueError(r"must validate the regular expression /^(native|stitch)$/")
        return value

    @field_validator('response_type')
    def response_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['BINARY', 'BASE64', 'URL']):
            raise ValueError("must be one of enum values ('BINARY', 'BASE64', 'URL')")
        return value

    @field_validator('url', mode="before")
    def url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^https?:\/\/.*", value):
            raise ValueError(r"must validate the regular expression /^https?:\/\/.*/")
        return value

    @field_validator('wait_until', mode="before")
    def wait_until_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^(load|domcontentloaded|networkidle)$", value):
            raise ValueError(r"must validate the regular expression /^(load|domcontentloaded|networkidle)$/")
        return value

    @field_validator('webhook_url', mode="before")
    def webhook_url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^https?:\/\/.*", value):
            raise ValueError(r"must validate the regular expression /^https?:\/\/.*/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScreenshotRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in actions (list)
        _items = []
        if self.actions:
            for _item_actions in self.actions:
                _items.append(_item_actions.to_dict() if _item_actions is not None else None)
            _dict['actions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in outputs (list)
        _items = []
        if self.outputs:
            for _item_outputs in self.outputs:
                _items.append(_item_outputs.to_dict() if _item_outputs is not None else None)
            _dict['outputs'] = _items
        # override the default output from pydantic by calling `to_dict()` of session
        if self.session:
            _dict['session'] = self.session.to_dict()
        # override the default output from pydantic by calling `to_dict()` of viewport
        if self.viewport:
            _dict['viewport'] = self.viewport.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if actions (nullable) is None
        # and model_fields_set contains the field
        if self.actions is None and "actions" in self.model_fields_set:
            _dict['actions'] = None

        # set to None if custom_css (nullable) is None
        # and model_fields_set contains the field
        if self.custom_css is None and "custom_css" in self.model_fields_set:
            _dict['customCss'] = None

        # set to None if device (nullable) is None
        # and model_fields_set contains the field
        if self.device is None and "device" in self.model_fields_set:
            _dict['device'] = None

        # set to None if hide_selectors (nullable) is None
        # and model_fields_set contains the field
        if self.hide_selectors is None and "hide_selectors" in self.model_fields_set:
            _dict['hideSelectors'] = None

        # set to None if max_height (nullable) is None
        # and model_fields_set contains the field
        if self.max_height is None and "max_height" in self.model_fields_set:
            _dict['maxHeight'] = None

        # set to None if outputs (nullable) is None
        # and model_fields_set contains the field
        if self.outputs is None and "outputs" in self.model_fields_set:
            _dict['outputs'] = None

        # set to None if selector (nullable) is None
        # and model_fields_set contains the field
        if self.selector is None and "selector" in self.model_fields_set:
            _dict['selector'] = None

        # set to None if session (nullable) is None
        # and model_fields_set contains the field
        if self.session is None and "session" in self.model_fields_set:
            _dict['session'] = None

        # set to None if viewport (nullable) is None
        # and model_fields_set contains the field
        if self.viewport is None and "viewport" in self.model_fields_set:
            _dict['viewport'] = None

        # set to None if wait_for (nullable) is None
        # and model_fields_set contains the field
        if self.wait_for is None and "wait_for" in self.model_fields_set:
            _dict['waitFor'] = None

        # set to None if webhook_secret (nullable) is None
        # and model_fields_set contains the field
        if self.webhook_secret is None and "webhook_secret" in self.model_fields_set:
            _dict['webhookSecret'] = None

        # set to None if webhook_url (nullable) is None
        # and model_fields_set contains the field
        if self.webhook_url is None and "webhook_url" in self.model_fields_set:
            _dict['webhookUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScreenshotRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "actions": [PageAction.from_dict(_item) for _item in obj["actions"]] if obj.get("actions") is not None else None,
            "blockAds": obj.get("blockAds") if obj.get("blockAds") is not None else True,
            "blockCookieBanners": obj.get("blockCookieBanners") if obj.get("blockCookieBanners") is not None else True,
            "blockLevel": obj.get("blockLevel") if obj.get("blockLevel") is not None else 'none',
            "blockPopups": obj.get("blockPopups") if obj.get("blockPopups") is not None else True,
            "customCss": obj.get("customCss"),
            "darkMode": obj.get("darkMode") if obj.get("darkMode") is not None else False,
            "delay": obj.get("delay") if obj.get("delay") is not None else 0,
            "device": obj.get("device"),
            "format": obj.get("format") if obj.get("format") is not None else 'png',
            "freezeFixed": obj.get("freezeFixed") if obj.get("freezeFixed") is not None else True,
            "fullPage": obj.get("fullPage") if obj.get("fullPage") is not None else False,
            "fullPageMode": obj.get("fullPageMode") if obj.get("fullPageMode") is not None else 'stitch',
            "hideSelectors": obj.get("hideSelectors"),
            "maxHeight": obj.get("maxHeight"),
            "maxSections": obj.get("maxSections") if obj.get("maxSections") is not None else 50,
            "outputs": [OutputSpec.from_dict(_item) for _item in obj["outputs"]] if obj.get("outputs") is not None else None,
            "quality": obj.get("quality") if obj.get("quality") is not None else 80,
            "responseType": obj.get("responseType") if obj.get("responseType") is not None else 'BINARY',
            "scrollInterval": obj.get("scrollInterval") if obj.get("scrollInterval") is not None else 150,
            "selector": obj.get("selector"),
            "session": BrowserSessionRequest.from_dict(obj["session"]) if obj.get("session") is not None else None,
            "stealthMode": obj.get("stealthMode") if obj.get("stealthMode") is not None else False,
            "timeout": obj.get("timeout") if obj.get("timeout") is not None else 30000,
            "url": obj.get("url"),
            "viewport": ViewportConfig.from_dict(obj["viewport"]) if obj.get("viewport") is not None else None,
            "waitFor": obj.get("waitFor"),
            "waitUntil": obj.get("waitUntil") if obj.get("waitUntil") is not None else 'domcontentloaded',
            "webhookSecret": obj.get("webhookSecret"),
            "webhookUrl": obj.get("webhookUrl")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


